{% set version = "2.1.2" %}

package:
  name: python-daemon
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-daemon/python-daemon-{{ version }}.tar.gz
  sha256: 261c859be5c12ae7d4286dc6951e87e9e1a70a882a8b41fd926efc1ec4214f73
  # https://pagure.io/python-daemon/issue/5
  patches:
    - fix_py3.patch  # [not win]

build:
  skip: True  # [win]
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - lockfile >=0.10
  run:
    - python
    - lockfile >=0.10
    - docutils

test:
  requires:
    - pip
  imports:
    - daemon
  commands:
    - python -m pip check

about:
  home: https://pagure.io/python-daemon/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.ASF-2
  summary: Library to implement a well-behaved Unix daemon process.
  dev_url: https://pagure.io/python-daemon/

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ocefpaf
